import type { StateDatabase } from "./database.ts";
import { EventStore } from "./event-store.ts";
import type { AgentRole, AttemptRecord, FindingRecord, GateName, GateResult, RunRecord, RunStatus, WorkflowState } from "../workflow/types.ts";
import { AnvilError } from "../util/errors.ts";

function now(): string { return new Date().toISOString(); }
function value<T>(row: Record<string, unknown>, key: string): T | undefined { const result = row[key]; return result === null || result === undefined ? undefined : result as T; }
function mapRun(row: Record<string, unknown>): RunRecord { return { id: row.id as string, workflowName: row.workflow_name as string, workflowVersion: row.workflow_version as number, configHash: row.config_hash as string, workspaceRoot: row.workspace_root as string, objectivePath: row.objective_path as string, planPath: value<string>(row, "plan_path"), baseRevisionId: row.base_revision_id as string, currentRevisionId: row.current_revision_id as string, mutationEpoch: row.mutation_epoch as number, currentState: row.current_state as WorkflowState, status: row.status as RunStatus, activeAttemptId: value<string>(row, "active_attempt_id"), maxTotalTokens: value<number>(row, "max_total_tokens"), maxTotalRequests: value<number>(row, "max_total_requests"), maxTransitions: value<number>(row, "max_transitions"), maxWallClockMs: value<number>(row, "max_wall_clock_ms"), usedTokens: row.used_tokens as number, usedInputTokens: row.used_input_tokens as number, usedOutputTokens: row.used_output_tokens as number, usedCacheReadTokens: row.used_cache_read_tokens as number, usedCacheWriteTokens: row.used_cache_write_tokens as number, usedRequests: row.used_requests as number, transitionCount: row.transition_count as number, createdAt: row.created_at as string, updatedAt: row.updated_at as string, startedAt: value<string>(row, "started_at"), finishedAt: value<string>(row, "finished_at"), blockedReason: value<string>(row, "blocked_reason"), failureCode: value<string>(row, "failure_code"), failureMessage: value<string>(row, "failure_message"), initialHead: row.initial_head as string }; }
function mapAttempt(row: Record<string, unknown>): AttemptRecord { return { id: row.id as string, runId: row.run_id as string, sequence: row.sequence as number, state: row.state as WorkflowState, role: value<AgentRole>(row, "role"), agentName: value<string>(row, "agent_name"), modelSelector: value<string>(row, "model_selector"), inputArtifactId: value<string>(row, "input_artifact_id"), outputArtifactId: value<string>(row, "output_artifact_id"), baseRevisionId: row.base_revision_id as string, resultRevisionId: value<string>(row, "result_revision_id"), status: row.status as AttemptRecord["status"], verdict: value<string>(row, "verdict"), inputTokens: row.input_tokens as number, outputTokens: row.output_tokens as number, cacheReadTokens: row.cache_read_tokens as number, cacheWriteTokens: row.cache_write_tokens as number, tokens: row.tokens as number, requests: row.requests as number, contextTokens: value<number>(row, "context_tokens"), contextWindow: value<number>(row, "context_window"), durationMs: value<number>(row, "duration_ms"), startedAt: row.started_at as string, endedAt: value<string>(row, "ended_at"), errorCode: value<string>(row, "error_code"), errorMessage: value<string>(row, "error_message") }; }
function mapGate(row: Record<string, unknown>): GateResult { return { id: row.id as string, runId: row.run_id as string, gate: row.gate as GateName, revisionId: row.revision_id as string, mutationEpoch: row.mutation_epoch as number, configHash: row.config_hash as string, gatePolicyHash: row.gate_policy_hash as string, verdict: row.verdict as GateResult["verdict"], attemptId: value<string>(row, "attempt_id"), artifactId: value<string>(row, "artifact_id"), startedAt: row.started_at as string, endedAt: row.ended_at as string }; }
function mapFinding(row: Record<string, unknown>): FindingRecord { return { id: row.id as string, runId: row.run_id as string, sourceGate: row.source_gate as GateName, fingerprint: row.fingerprint as string, severity: row.severity as string, category: row.category as string, title: row.title as string, description: row.description as string, fixRequirement: value<string>(row, "fix_requirement"), filePath: value<string>(row, "file_path"), lineStart: value<number>(row, "line_start"), lineEnd: value<number>(row, "line_end"), status: row.status as FindingRecord["status"], firstSeenEpoch: row.first_seen_epoch as number, lastSeenEpoch: row.last_seen_epoch as number, timesSeen: row.times_seen as number, reopenCount: row.reopen_count as number, firstAttemptId: row.first_attempt_id as string, lastAttemptId: row.last_attempt_id as string, evidenceArtifactId: value<string>(row, "evidence_artifact_id"), resolvedAttemptId: value<string>(row, "resolved_attempt_id"), resolutionNote: value<string>(row, "resolution_note"), createdAt: row.created_at as string, updatedAt: row.updated_at as string }; }

export class RunRepository {
  constructor(private readonly state: StateDatabase, private readonly events = new EventStore(state)) {}
  create(input: Omit<RunRecord, "createdAt" | "updatedAt" | "status" | "currentState" | "usedTokens" | "usedInputTokens" | "usedOutputTokens" | "usedCacheReadTokens" | "usedCacheWriteTokens" | "usedRequests" | "transitionCount">): RunRecord {
    const timestamp = now(); const run: RunRecord = { ...input, createdAt: timestamp, updatedAt: timestamp, status: "running", currentState: "INIT", usedTokens: 0, usedInputTokens: 0, usedOutputTokens: 0, usedCacheReadTokens: 0, usedCacheWriteTokens: 0, usedRequests: 0, transitionCount: 0 };
    this.state.db.run("INSERT INTO runs(id, workflow_name, workflow_version, config_hash, workspace_root, objective_path, plan_path, base_revision_id, current_revision_id, mutation_epoch, current_state, status, max_total_tokens, max_total_requests, max_transitions, max_wall_clock_ms, created_at, updated_at, started_at, initial_head) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [run.id, run.workflowName, run.workflowVersion, run.configHash, run.workspaceRoot, run.objectivePath, run.planPath ?? null, run.baseRevisionId, run.currentRevisionId, 0, "INIT", "running", run.maxTotalTokens ?? null, run.maxTotalRequests ?? null, run.maxTransitions ?? null, run.maxWallClockMs ?? null, timestamp, timestamp, timestamp, run.initialHead]);
    this.events.append({ runId: run.id, type: "RUN_CREATED", actor: "anvil", stateAfter: "INIT", revisionId: run.currentRevisionId }); return run;
  }
  require(id: string): RunRecord { const row = this.state.db.query<Record<string, unknown>>("SELECT * FROM runs WHERE id = ?").get(id); if (!row) throw new AnvilError("RUN_NOT_FOUND", `Run not found: ${id}`); return mapRun(row); }
  latest(): RunRecord | undefined { const row = this.state.db.query<Record<string, unknown>>("SELECT * FROM runs ORDER BY created_at DESC LIMIT 1").get(); return row ? mapRun(row) : undefined; }
  update(id: string, patch: Partial<Record<string, unknown>>, event?: { type: string; actor?: string; stateBefore?: string; stateAfter?: string; revisionId?: string; payload?: unknown }): RunRecord { const allowed = new Set(["plan_path", "current_revision_id", "mutation_epoch", "current_state", "status", "active_attempt_id", "max_total_tokens", "max_total_requests", "max_transitions", "max_wall_clock_ms", "used_tokens", "used_input_tokens", "used_output_tokens", "used_cache_read_tokens", "used_cache_write_tokens", "used_requests", "transition_count", "updated_at", "started_at", "finished_at", "blocked_reason", "failure_code", "failure_message"]); const entries = Object.entries(patch).filter(([key]) => allowed.has(key)); if (entries.length > 0) { const assignments = entries.map(([key]) => `${key} = ?`).join(", "); this.state.db.run(`UPDATE runs SET ${assignments}, updated_at = ? WHERE id = ?`, [...entries.map(([, field]) => field), now(), id]); } if (event) this.events.append({ runId: id, actor: event.actor ?? "anvil", ...event }); return this.require(id); }
  beginAttempt(run: RunRecord, state: WorkflowState, role: AgentRole | undefined, agentName: string): AttemptRecord { const row = this.state.db.query<{ sequence: number }>("SELECT COALESCE(MAX(sequence), 0) + 1 AS sequence FROM attempts WHERE run_id = ?").get(run.id); const attempt: AttemptRecord = { id: `att_${crypto.randomUUID()}`, runId: run.id, sequence: row?.sequence ?? 1, state, role, agentName, baseRevisionId: run.currentRevisionId, status: "running", inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, tokens: 0, requests: 0, startedAt: now() }; this.state.db.run("INSERT INTO attempts(id, run_id, sequence, state, role, agent_name, base_revision_id, status, started_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", [attempt.id, run.id, attempt.sequence, state, role ?? null, agentName, run.currentRevisionId, "running", attempt.startedAt]); this.update(run.id, { active_attempt_id: attempt.id }); return attempt; }
  finalizeAttempt(attempt: AttemptRecord, result: { status: AttemptRecord["status"]; resultRevisionId?: string; verdict?: string; usage?: { input?: number; output?: number; cacheRead?: number; cacheWrite?: number; total?: number; requests?: number; contextTokens?: number; contextWindow?: number }; durationMs?: number; error?: { code: string; message: string } }): void { const usage = result.usage ?? {}; const tokens = usage.total ?? ((usage.input ?? 0) + (usage.output ?? 0)); this.state.db.run("UPDATE attempts SET status = ?, result_revision_id = ?, verdict = ?, input_tokens = ?, output_tokens = ?, cache_read_tokens = ?, cache_write_tokens = ?, tokens = ?, requests = ?, context_tokens = ?, context_window = ?, duration_ms = ?, ended_at = ?, error_code = ?, error_message = ? WHERE id = ?", [result.status, result.resultRevisionId ?? null, result.verdict ?? null, usage.input ?? 0, usage.output ?? 0, usage.cacheRead ?? 0, usage.cacheWrite ?? 0, tokens, usage.requests ?? 0, usage.contextTokens ?? null, usage.contextWindow ?? null, result.durationMs ?? null, now(), result.error?.code ?? null, result.error?.message ?? null, attempt.id]); const run = this.require(attempt.runId); this.update(run.id, { active_attempt_id: null, used_tokens: run.usedTokens + tokens, used_input_tokens: run.usedInputTokens + (usage.input ?? 0), used_output_tokens: run.usedOutputTokens + (usage.output ?? 0), used_cache_read_tokens: run.usedCacheReadTokens + (usage.cacheRead ?? 0), used_cache_write_tokens: run.usedCacheWriteTokens + (usage.cacheWrite ?? 0), used_requests: run.usedRequests + (usage.requests ?? 0) }); }
  attempts(runId: string): AttemptRecord[] { return this.state.db.query<Record<string, unknown>>("SELECT * FROM attempts WHERE run_id = ? ORDER BY sequence").all(runId).map(mapAttempt); }
  attemptsFor(runId: string, state: WorkflowState): AttemptRecord[] { return this.attempts(runId).filter((attempt) => attempt.state === state); }
  markRunningInterrupted(runId: string): AttemptRecord | undefined { const attempt = this.attempts(runId).find((item) => item.status === "running"); if (!attempt) return undefined; this.state.db.run("UPDATE attempts SET status = 'interrupted', ended_at = ? WHERE id = ?", [now(), attempt.id]); return { ...attempt, status: "interrupted", endedAt: now() }; }
}

export class GateRepository {
  constructor(private readonly state: StateDatabase) {}
  save(input: Omit<GateResult, "id">): GateResult { const result = { ...input, id: `gate_${crypto.randomUUID()}` }; this.state.db.run("INSERT OR REPLACE INTO gate_results(id, run_id, gate, revision_id, mutation_epoch, config_hash, gate_policy_hash, verdict, attempt_id, artifact_id, started_at, ended_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [result.id, result.runId, result.gate, result.revisionId, result.mutationEpoch, result.configHash, result.gatePolicyHash, result.verdict, result.attemptId ?? null, result.artifactId ?? null, result.startedAt, result.endedAt]); return result; }
  latestPassing(runId: string, gate: GateName): GateResult | undefined { const row = this.state.db.query<Record<string, unknown>>("SELECT * FROM gate_results WHERE run_id = ? AND gate = ? ORDER BY rowid DESC LIMIT 1").get(runId, gate); return row?.verdict === "pass" ? mapGate(row) : undefined; }
  currentPass(runId: string, gate: GateName, revisionId: string, configHash: string, policyHash: string): GateResult | undefined { const latest = this.latestPassing(runId, gate); return latest?.revisionId === revisionId && latest.configHash === configHash && latest.gatePolicyHash === policyHash ? latest : undefined; }
}

export class FindingRepository {
  constructor(private readonly state: StateDatabase) {}
  list(runId: string, status?: string): FindingRecord[] { const rows = status ? this.state.db.query<Record<string, unknown>>("SELECT * FROM findings WHERE run_id = ? AND status = ? ORDER BY created_at").all(runId, status) : this.state.db.query<Record<string, unknown>>("SELECT * FROM findings WHERE run_id = ? ORDER BY created_at").all(runId); return rows.map(mapFinding); }
  hasBlocking(runId: string, blocking: string[]): boolean { const findings = this.list(runId, "open"); return findings.some((finding) => blocking.includes(finding.severity)); }
  upsert(input: Omit<FindingRecord, "id" | "createdAt" | "updatedAt" | "status" | "timesSeen" | "reopenCount">): FindingRecord { const existing = this.state.db.query<Record<string, unknown>>("SELECT * FROM findings WHERE run_id = ? AND source_gate = ? AND fingerprint = ?").get(input.runId, input.sourceGate, input.fingerprint); const timestamp = now(); if (!existing) { const finding: FindingRecord = { ...input, id: `${input.sourceGate.slice(0, 3).toUpperCase()}-${crypto.randomUUID()}`, status: "open", timesSeen: 1, reopenCount: 0, createdAt: timestamp, updatedAt: timestamp }; this.state.db.run("INSERT INTO findings(id, run_id, source_gate, fingerprint, severity, category, title, description, fix_requirement, file_path, line_start, line_end, status, first_seen_epoch, last_seen_epoch, times_seen, reopen_count, first_attempt_id, last_attempt_id, evidence_artifact_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [finding.id, finding.runId, finding.sourceGate, finding.fingerprint, finding.severity, finding.category, finding.title, finding.description, finding.fixRequirement ?? null, finding.filePath ?? null, finding.lineStart ?? null, finding.lineEnd ?? null, finding.status, finding.firstSeenEpoch, finding.lastSeenEpoch, 1, 0, finding.firstAttemptId, finding.lastAttemptId, finding.evidenceArtifactId ?? null, timestamp, timestamp]); return finding; }
    const prior = mapFinding(existing); const reopened = prior.status === "resolved"; this.state.db.run("UPDATE findings SET severity = ?, description = ?, fix_requirement = ?, file_path = ?, line_start = ?, line_end = ?, status = 'open', last_seen_epoch = ?, times_seen = ?, reopen_count = ?, last_attempt_id = ?, evidence_artifact_id = ?, updated_at = ? WHERE id = ?", [input.severity, input.description, input.fixRequirement ?? null, input.filePath ?? null, input.lineStart ?? null, input.lineEnd ?? null, input.lastSeenEpoch, prior.timesSeen + 1, prior.reopenCount + (reopened ? 1 : 0), input.lastAttemptId, input.evidenceArtifactId ?? null, timestamp, prior.id]); return { ...prior, ...input, status: "open", timesSeen: prior.timesSeen + 1, reopenCount: prior.reopenCount + (reopened ? 1 : 0), updatedAt: timestamp }; }
  resolveGate(runId: string, sourceGate: GateName, attemptId: string): void { this.state.db.run("UPDATE findings SET status = 'resolved', resolved_attempt_id = ?, resolution_note = ?, updated_at = ? WHERE run_id = ? AND source_gate = ? AND status = 'open'", [attemptId, "Full gate pass on current revision", now(), runId, sourceGate]); }
}
