import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { runProcess } from "./runners/process.ts";

export type UpdateAction = "check" | "install";
export interface ReleaseInfo { version: string; tag: string; url: string; }
export interface UpdateReport { currentVersion: string; latestVersion: string | null; updateAvailable: boolean; releaseUrl: string | null; managed: boolean; updated?: boolean; message?: string; }
export class UpdateError extends Error { constructor(message: string) { super(message); this.name = "UpdateError"; } }

const REPOSITORY = "MSpiechowicz/oh-my-pi-anvil";
const MARKETPLACE = "omp-anvil";
const PLUGIN_ID = "oh-my-pi-anvil@omp-anvil";
const RELEASE_API = `https://api.github.com/repos/${REPOSITORY}/releases/latest`;
const RELEASE_BASE = `https://github.com/${REPOSITORY}/releases/tag/`;
const MODULE_DIRECTORY = path.dirname(fileURLToPath(import.meta.url));
const PACKAGE_ROOT = ["src", "dist"].includes(path.basename(MODULE_DIRECTORY))
  ? path.resolve(MODULE_DIRECTORY, "..")
  : MODULE_DIRECTORY;
const SEMVER = /^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$/;

function versionTuple(value: string): [number, number, number] { const match = SEMVER.exec(value); if (!match) throw new UpdateError("Expected a stable MAJOR.MINOR.PATCH version."); return [Number(match[1]), Number(match[2]), Number(match[3])]; }
function newer(left: string, right: string): boolean { const a = versionTuple(left); const b = versionTuple(right); return a[0] !== b[0] ? a[0] > b[0] : a[1] !== b[1] ? a[1] > b[1] : a[2] > b[2]; }
async function packageVersion(root = PACKAGE_ROOT): Promise<string> { try { const packageJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8")) as { version?: string }; if (!packageJson.version) throw new Error("missing version"); versionTuple(packageJson.version); return packageJson.version; } catch (error) { throw new UpdateError(`Cannot read a valid Anvil package version: ${error instanceof Error ? error.message : String(error)}`); } }

export async function latestRelease(fetcher: typeof fetch = fetch): Promise<ReleaseInfo | null> { let response: Response; try { response = await fetcher(RELEASE_API, { headers: { Accept: "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28", "User-Agent": "omp-anvil-updater" }, redirect: "error" }); } catch (error) { throw new UpdateError(`Cannot retrieve the public GitHub release: ${error instanceof Error ? error.message : String(error)}`); } if (response.status === 404) return null; if (!response.ok) throw new UpdateError(`GitHub release request failed (HTTP ${response.status}).`); const body = await response.arrayBuffer(); if (body.byteLength > 1024 * 1024) throw new UpdateError("GitHub release response exceeded the size limit."); let data: unknown; try { data = JSON.parse(new TextDecoder().decode(body)); } catch { throw new UpdateError("GitHub returned invalid release metadata."); } if (!data || typeof data !== "object") throw new UpdateError("GitHub returned invalid release metadata."); const release = data as { draft?: unknown; prerelease?: unknown; tag_name?: unknown }; if (release.draft !== false || release.prerelease !== false || typeof release.tag_name !== "string" || !release.tag_name.startsWith("v")) throw new UpdateError("GitHub did not return a published stable release."); const version = release.tag_name.slice(1); versionTuple(version); return { version, tag: release.tag_name, url: RELEASE_BASE + release.tag_name }; }

interface NativePlugin { id?: string; scope?: string; shadowedBy?: unknown; entries?: Array<{ enabled?: boolean; scope?: string; installPath?: string; version?: string }>; }
interface ManagedInstallation { scope: "user" | "project"; installPath: string; version: string; }
async function native(profile: string | undefined, args: string[], timeoutMs: number, cwd: string): Promise<string> { const command = ["omp"]; if (profile) command.push("--profile", profile); command.push("plugin", ...args); const result = await runProcess(command, { cwd, timeoutMs }); if (result.status !== "passed") throw new UpdateError(`OMP plugin ${args[0] ?? "operation"} failed; inspect the native OMP command output and retry.`); return result.stdout; }
function marketplaceEntries(data: unknown): NativePlugin[] { if (!data || typeof data !== "object" || !("marketplace" in data) || !Array.isArray(data.marketplace)) throw new UpdateError("OMP does not support `omp plugin list --json`; upgrade OMP before updating Anvil."); return data.marketplace as NativePlugin[]; }
async function installedPlugins(profile: string | undefined, cwd: string): Promise<NativePlugin[]> { let data: unknown; try { data = JSON.parse(await native(profile, ["list", "--json"], 8000, cwd)); } catch (error) { if (error instanceof UpdateError) throw error; throw new UpdateError("Cannot read native OMP marketplace installations."); } return marketplaceEntries(data); }
async function managedInstallation(profile: string | undefined, expectedRoot: string | undefined, cwd: string): Promise<ManagedInstallation | undefined> { const matches: ManagedInstallation[] = []; for (const summary of await installedPlugins(profile, cwd)) { if (summary.id !== PLUGIN_ID || (summary.scope !== "user" && summary.scope !== "project") || summary.shadowedBy || !summary.entries || summary.entries.length !== 1) continue; const entry = summary.entries[0]; if (entry.enabled === false || entry.scope !== summary.scope || !entry.installPath || !path.isAbsolute(entry.installPath) || (expectedRoot && path.resolve(entry.installPath) !== path.resolve(expectedRoot))) continue; const version = await packageVersion(entry.installPath); if (entry.version !== version) throw new UpdateError("OMP registry and installed Anvil versions disagree; inspect `omp plugin list` before updating."); matches.push({ scope: summary.scope, installPath: path.resolve(entry.installPath), version }); } if (matches.length > 1) throw new UpdateError("Anvil has multiple active marketplace installations; remove the ambiguity before updating."); return matches[0]; }

export async function checkUpdate(profile?: string, cwd = process.cwd()): Promise<UpdateReport> { const currentVersion = await packageVersion(); const release = await latestRelease(); const managed = Boolean(await managedInstallation(profile, PACKAGE_ROOT, cwd)); const report: UpdateReport = { currentVersion, latestVersion: release?.version ?? null, updateAvailable: Boolean(release && managed && newer(release.version, currentVersion)), releaseUrl: release?.url ?? null, managed }; if (!report.managed) report.message = "This Anvil installation is not an unambiguous active OMP marketplace installation. Source checkouts are updated with git pull and a rebuild."; else if (!release) report.message = "No published stable GitHub release is available."; return report; }
export async function installUpdate(profile?: string, cwd = process.cwd()): Promise<UpdateReport> { const initial = await managedInstallation(profile, PACKAGE_ROOT, cwd); if (!initial) throw new UpdateError("This Anvil installation is not an unambiguous active OMP marketplace installation. Source checkouts are never overwritten."); const currentVersion = await packageVersion(); const release = await latestRelease(); const report: UpdateReport = { currentVersion, latestVersion: release?.version ?? null, updateAvailable: release ? newer(release.version, currentVersion) : false, releaseUrl: release?.url ?? null, managed: true }; if (!release || !report.updateAvailable) return { ...report, updated: false, message: "No newer stable release is available." }; await native(profile, ["marketplace", "update", MARKETPLACE], 55000, cwd); const stillInitial = await managedInstallation(profile, PACKAGE_ROOT, cwd); if (!stillInitial || stillInitial.scope !== initial.scope || stillInitial.installPath !== initial.installPath || stillInitial.version !== initial.version) throw new UpdateError("The native installation changed during the update check; inspect it before retrying."); await native(profile, ["upgrade", PLUGIN_ID, "--scope", initial.scope], 75000, cwd); const installed = await managedInstallation(profile, undefined, cwd); if (!installed || installed.scope !== initial.scope || !newer(installed.version, currentVersion)) throw new UpdateError("OMP did not install a newer stable Anvil release; the marketplace may not have published it yet."); return { ...report, currentVersion: installed.version, updated: true, message: `Updated to ${installed.version} using OMP plugin upgrade. Restart OMP to load the updated extension.` }; }
export async function runUpdate(action: UpdateAction, profile?: string, cwd = process.cwd()): Promise<UpdateReport> { return action === "check" ? checkUpdate(profile, cwd) : installUpdate(profile, cwd); }
